name: CI

on: [push]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}
    - name: Atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: Install dependencies
      run: apm ci
    - name: Run tests
      run: atom --test spec
