name: Publish to Atom.io

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:
        version: stable
    - name: Atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - run: echo '${{ $GITHUB_REF }}'
    - run: echo `$GITHUB_REF'
    - name: Publish
      run: apm publish --tag $GITHUB_REF
