name: Unpublish from Atom.io

on:
  release:
    types: [ unpublished ]

jobs:
  unpublish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:
        version: stable
    - name: Atom version
      run: atom -v
    - name: apm version
      run: apm -v
    - name: Unpublish
      run: apm unpublish --tag $GITHUB_REF
